### PR TITLE
relicense to MIT

### LINKED ISSUE #183: switch to MIT license
The WTFPL causes people to not want to use this library. Historically, I've been against changing the license mostly because it's just a pain to do so. Ideally, we'd like to get a sign off from all people that have made non-trivial contributions. (And if we can't, we either need to stop the re-licensing process or remove/rewrite those contributions. I'm not particularly inclined to the do latter, but if we can do the former, than we should.)

So, this issue is going to track the relicensing progress. I'll start by listing some of the major contributors, where I interpreted "major" as "100 lines of code or more."

* [x] @BurntSushi
* [x] @cespare 
* [x] @sqs
* [x] @rjeczalik
* [x] @ttacon
* [x] @bbuck
* [x] @halostatue
* [x] @sethwklein

### PR DESCRIPTION
**Pull request by BurntSushi**
Closes #183

### CODE REVIEW

**Comment by ryanwalls** [comment]
@BurntSushi Just curious.  Why COPYING instead of LICENSE?  Our automated tools for license checking don't pick up the COPYING file... so I have to manually come here.  Then I couldn't find the license file, so I search issues to find the issue about switching to MIT #183.  Then I had to look at this PR that closed that to then find that the file was called COPYING.  Whew.  :)

**Comment by BurntSushi** [comment]
@ryanwalls `COPYING` is a standard name for the license file.

**Comment by ryanwalls** [comment]
@BurntSushi Ah.  Good to know.  Didn't realize it was standard.  Will send a PR to the licensing tool I'm using.  https://github.com/pivotal/LicenseFinder

**Comment by ryanwalls** [comment]
@BurntSushi Since this has come up before, see https://github.com/kubernetes/kubernetes/pull/31024, it would seem a small change to standardize.  But I understand if it is a low priority.

**Pull request merged**
