### PR TITLE
Go1.16 fix

### PR DESCRIPTION
**Pull request by ando-masaki**
I changed by following command.
```
$ go version
go version go1.16.2 linux/amd64
$ rm go.* && go mod init && go mod tidy
```

Because I found error while testing by go1.16.

```
$ cd path/to/repo
$ go test -v ./...
missing go.sum entry for module providing package github.com/BurntSushi/toml
```

### CODE REVIEW

**Comment by ando-masaki** [comment]
This pill request is version down for `toml-test`.
```diff
-require github.com/BurntSushi/toml-test v0.1.1-0.20210704114940-e6948edce1c5
+require github.com/BurntSushi/toml-test v0.1.0
```
Because there is no tags  named `v0.1.1` in https://github.com/BurntSushi/toml-test/releases .
Please tell me how to solve this problem.

**Comment by arp242** [comment]
The "v0.1.1" is just a fake tag it puts in there if you use a specific commit.

What is the problem you're having exactly?

**Comment by ando-masaki** [comment]
I'm sorry. It was no problem. My private repo's go.mod setting was wrong. I close this pull request.

**Comment by arp242** [comment]
Cheers; no worries :-)

**Pull request closed without merging**
