### PR TITLE
Support all integer types

### PR DESCRIPTION
**Pull request by thayama**
According to the TOML spec, we should be able to represent hexadecimal, octal, and binary notations. This changes add support for these notations.

I'd appreciate if you could consider taking these changes.

### CODE REVIEW

**Comment by tzneal** [comment]
I would like to see this merged in as well.

**Comment by thayama** [comment]
Do you want the same or similar coverage as `TestDecodeInts` and `TestDecodeMalformedNumbers`?

**Comment by vigo5190** [comment]
some updates?

**Comment by thayama** [comment]
@BurntSushi Do you need more tests?

**Comment by Felixoid** [comment]
Hello, is there any planning to merge it?

**Comment by arp242** [comment]
I'm closing this one in favour of #260, which seems like a slightly better patch. I still need to review/merge that, but I'll do that soon and closing it now clears the PR list a bit 😅

**Pull request closed without merging**
