### PR TITLE
change eindirect behave match with indirect from decode

### PR DESCRIPTION
**Pull request by kkHAIKE**
fix https://github.com/BurntSushi/toml/issues/357

### CODE REVIEW

**Comment by arp242** [comment]
Thanks!

One thing that's missing is a few tests that test the new behaviour.

**Comment by kkHAIKE** [comment]
add test.
but i found origin TestEncodeTextMarshaler has bug with Sound field. when change Encode obj to '&x', but use my fix is work around....nnn

output:
```toml
Name = "Goblok"

[Sound]
  S = "miauw"
Sound2 = "miauw"
Food = "chicken, fish"
Food2 = "chicken, fish"
Complex = "(42.000000+666.000000i)"
Fun = "why would you do this?"

[Labels]
  color = "black"
  type = "cat"
```

**Comment by kkHAIKE** [comment]
i found other bug with embed private struct/interface, let me make new commit

**Comment by kkHAIKE** [comment]
fixed with privete embed struct / nostruct field, behaviour like json.Marshal

**Comment by arp242** [comment]
> but i found origin TestEncodeTextMarshaler has bug with Sound field. when change Encode obj to '&x', but use my fix is work around

Yeah, that's expected; that's what I mentioned in the issue as well.

Anyway, seems good at a glance, but I'll go over your PR in detail later.

**Comment by arp242** [comment]
Thank you!

**Comment by kkHAIKE** [comment]
Can you create a new tag for last commit 😊

**Comment by arp242** [comment]
I want to pick up a few more small things before a new release @kkHAIKE, because then all non-v2 issues are resolved and I can start working on that. In the meanwhile, you can use a new version in your project by using `go get github.com/BurntSushi/toml@master` (you don't *need* a tagged release to get this patch).

**Pull request merged**
